server:
  port: 8085
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: LOCAL
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none