server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none